### PR TITLE
test ci

### PR DESCRIPTION
**Pull request by vrindle**

### CODE REVIEW

**Comment by vrindle** [comment]
@wizhaoredhat

**Comment by SchSeba** [comment]
Hi @vrindle @wizhaoredhat what are you trying to test?

**Comment by vrindle** [comment]
> Hi @vrindle @wizhaoredhat what are you trying to test?

Hi @SchSeba. The CI is failing for this PR. https://github.com/k8snetworkplumbingwg/network-resources-injector/pull/147. I opened this PR up to test if my specific changes were causing The CI failure or if it’s a separate issue.

**Comment by SchSeba** [comment]
Hi @vrindle please do a rebase on https://github.com/k8snetworkplumbingwg/network-resources-injector/pull/147 and push there is a new CI lane that test this on k8s until we fix the kind one

**Comment by SchSeba** [comment]
closing this one

**Pull request closed without merging**
