### PR TITLE
Add E2E KinD test and GA

### PR DESCRIPTION
**Pull request by martinkennelly**

### CODE REVIEW

**Comment by zshi-redhat** [comment]
I followed the test/README.md, it mostly worked! Thanks for the nice work @martinkennelly !

When executing the test with `go test ./test/e2e/...`, hit a dependency error:
```
go: gopkg.in/intel/multus-cni.v3@v3.4.2 requires
	github.com/k8snetworkplumbingwg/network-attachment-definition-client@v0.0.0-20200127152046-0ee521d56061 requires
	k8s.io/code-generator@v0.0.0-20181114232248-ae218e241252 requires
	gonum.org/v1/netlib@v0.0.0-20190331212654-76723241ea4e requires
	modernc.org/cc@v1.0.0: reading modernc.org/cc/go.mod at revision v1.0.0: unknown revision v1.0.0
```
Did you see the same?

**Comment by martinkennelly** [comment]
@zshi-redhat No, I have not seen this. I also do not see it on the GitHub actions VM executing this test. What version of golang are you using?

**Comment by zshi-redhat** [comment]
> @zshi-redhat No, I have not seen this. I also do not see it on the GitHub actions VM executing this test. What version of golang are you using?

I was using `go version go1.15.8 linux/amd64`.

**Comment by martinkennelly** [comment]
> > @zshi-redhat No, I have not seen this. I also do not see it on the GitHub actions VM executing this test. What version of golang are you using?
> 
> I was using `go version go1.15.8 linux/amd64`.

Thank you. If you see this GAs execution, there is no error either with dependencies on a clean ubuntu VM: https://github.com/k8snetworkplumbingwg/network-resources-injector/runs/1982049446?check_suite_focus=true

**Comment by zshi-redhat** [comment]
> > > @zshi-redhat No, I have not seen this. I also do not see it on the GitHub actions VM executing this test. What version of golang are you using?
> > 
> > 
> > I was using `go version go1.15.8 linux/amd64`.
> 
> Thank you. If you see this GAs execution, there is no error either with dependencies on a clean ubuntu VM: https://github.com/k8snetworkplumbingwg/network-resources-injector/runs/1982049446?check_suite_focus=true

I tried this again in a clean environment, this time there is no go dependency error.
the e2e test passed.

Thanks @martinkennelly !

**Comment by zshi-redhat** [comment]
@martinkennelly  Would you mind rebase the PR, then we can merge it?

**Comment by martinkennelly** [comment]
@zshi-redhat Done.

**Comment by martinkennelly** [comment]
@zshi-redhat This is going to be fantastic long term once we can add enough cases to cover our features! I am excited! Thank you for the reviews! Thank you for starting this initiative!

**Comment by zshi-redhat** [comment]
> @zshi-redhat This is going to be fantastic long term once we can add enough cases to cover our features! I am excited! Thank you for the reviews! Thank you for starting this initiative!

@martinkennelly You did a great work adding these initial scripts and cases!  I knew it is not trivial and requires a bit amount of development and testing. Thanks for you dedication and contribution! I'm looking forward to seeing more cases be added and the same methodology be applied to other projects as well. Cheers!

**Pull request merged**
