### PR TITLE
Add build and test GitHub action

### PR DESCRIPTION
**Pull request by martinkennelly**
Part of issue #68

### CODE REVIEW

**Comment by martinkennelly** [comment]
I was thinking - you can also add cron job to these actions - do we want to add this to this PR? Twice a week ?

**Comment by martinkennelly** [comment]
Added support for test and build for multiple golang versions.
#74 needs to be merged before this GA executes correctly.

**Comment by zshi-redhat** [comment]
> Added support for test and build for multiple golang versions.
> #74 needs to be merged before this GA executes correctly.

#74 was merged, shall we re-run the workflow?

**Comment by martinkennelly** [comment]
@zshi-redhat rebased against master to trigger workflow tests.

**Review by zshi-redhat — APPROVED** [review]

**Pull request merged**
