### PR TITLE
E2E tests for numerous NRI features

### PR DESCRIPTION
**Pull request by martinkennelly**
E2E Tests for features:
  * node selector
  * hugepages (optional)
  * user defined injections
  * resourceName

Co-authored-by: Michal Guzieniuk <michalx.guzieniuk@intel.com>
Co-authored-by: Martin Kennelly <martin.kennelly@intel.com>

Hugepages test is optional and will be skipped if the number of 1Gi / 2Mi hugepages arent available. This allows us to run the same tests in an environment with (self hosted) and without hugepages (GH VM).

This patch adds a self hosted job which requires a GH environment. A GH environment can contain a set of approvers to allow execution. This environment should be created before this patch can be merged and tested.

Example of how we can use GH environments to allow a set of people to approve workflows: [https://docs.google.com/document/d/1kWko-Hnne-BcuFvzEZPlmGxFQ9FSkTzPSzxP1m9xUuY/edit](https://docs.google.com/document/d/1kWko-Hnne-BcuFvzEZPlmGxFQ9FSkTzPSzxP1m9xUuY/edit)

Thanks to @MichalGuzieniuk for creating all the tests.

Sample execution: https://github.com/martinkennelly/network-resources-injector/runs/2504160518?check_suite_focus=true

### CODE REVIEW

**Comment by martinkennelly** [comment]
@MichalGuzieniuk any idea why this failing:

``` [Fail] Verify 'User Defined Injections' Positive use cases - expected that NRI will inject correctly custom definitions [It] Config map in correct namespace, TWO labels to inject, POD specification WITH resource name 
/home/github/actions-runner/_work/network-resources-injector/network-resources-injector/test/e2e/custominection_test.go:123 
```

**Comment by MichalGuzieniuk** [comment]
> @MichalGuzieniuk any idea why this failing:
> 
> ```
> /home/github/actions-runner/_work/network-resources-injector/network-resources-injector/test/e2e/custominection_test.go:123 
> ```

I have checked this test and there is an issue inside NRI implementation. It does not allows to inject two labels or in other words it injects randomly only one. Some time ago, I have reported this at https://github.com/k8snetworkplumbingwg/network-resources-injector/issues/94

@martinkennelly What do you think about excluding this test with comment inside issue?

**Comment by martinkennelly** [comment]
> > @MichalGuzieniuk any idea why this failing:
> > ```
> > /home/github/actions-runner/_work/network-resources-injector/network-resources-injector/test/e2e/custominection_test.go:123 
> > ```
> 
> I have checked this test and there is an issue inside NRI implementation. It does not allows to inject two labels or in other words it injects randomly only one. Some time ago, I have reported this at #94
> 
> @martinkennelly What do you think about excluding this test with comment inside issue?

Thanks @MichalGuzieniuk 
I think we should leave it until we decide how we will handle it. Last thing I want is to ignore this issue. Do you want to fix it Michal?

**Comment by MichalGuzieniuk** [comment]
> > > @MichalGuzieniuk any idea why this failing:
> > > ```
> > > /home/github/actions-runner/_work/network-resources-injector/network-resources-injector/test/e2e/custominection_test.go:123 
> > > ```
> > 
> > 
> > I have checked this test and there is an issue inside NRI implementation. It does not allows to inject two labels or in other words it injects randomly only one. Some time ago, I have reported this at #94
> > @martinkennelly What do you think about excluding this test with comment inside issue?
> 
> Thanks @MichalGuzieniuk
> I think we should leave it until we decide how we will handle it. Last thing I want is to ignore this issue. Do you want to fix it Michal?

@martinkennelly yes, I may fix it when I will finish with tests. Question is if such functionality is needed within NRI?

**Comment by martinkennelly** [comment]
rebased upon current master

**Comment by Eoghan1232** [comment]
Closing this PR. 
It will be continued in #121.

**Pull request closed without merging**
